### ISSUE TITLE
user data

### ISSUE THREAD

**Issue by hoangdzung** [rpasricha/TransFM#3]
How do you get the csv file with numeric features of users? Thanks for your help.

**Comment by rpasricha** [comment]
Hi, you can find the data used in the paper at the following link: https://cseweb.ucsd.edu/~jmcauley/datasets.html. 

Please let me know if you have any additional questions.

**Comment by hoangdzung** [comment]
Yeah, I know this site. But how do you convert the attributes in string format into numbers? Just something like LabelEncoder of sklearn?

**Comment by rpasricha** [comment]
Yes, I converted the string attributes into numeric indices. There's no inherent meaning assigned to each number. 

LabelEncoder would perform the same transformation.

**Comment by hoangdzung** [comment]
Ok. I got it. Thanks for your help.
